### ISSUE TITLE
Markbot expected content I'm not successfully inputting

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/dinosaur-designs#1]
@thomasjbradley

<img width="796" alt="screen shot 2018-09-28 at 12 46 54 am" src="https://user-images.githubusercontent.com/19557909/46188606-28423a00-c2b8-11e8-9333-ae16f9705799.png">
<img width="520" alt="screen shot 2018-09-28 at 12 47 15 am" src="https://user-images.githubusercontent.com/19557909/46188607-28423a00-c2b8-11e8-8bdd-477beb67d4d8.png">
<img width="556" alt="screen shot 2018-09-28 at 12 48 17 am" src="https://user-images.githubusercontent.com/19557909/46188626-3b550a00-c2b8-11e8-8e9a-4692dd6723d5.png">

Is this where Markbot wants this content?

**Comment by thomasjbradley** [comment]
The code has straight quotes, not proper typography curly quotes. Copy and paste from the `content.txt` file to get the correct quotes.

**Comment by MacKenzieRose** [comment]
Worked like a charm. Thank you 👍
